import { useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import logo from "./assets/logo.png";
import "./App.css";

function App() {
  const [zip, setZip] = useState("32801");
  const [agentName, setAgentName] = useState("Harshitha");
  const [agentEmail, setAgentEmail] = useState("harshithanarahari25@gmail.com");
  const [agentPhone, setAgentPhone] = useState("+1 555-123-4567");
  const [preview, setPreview] = useState(null);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);

  const generate = async () => {
    setLoading(true);
    const res = await fetch(`http://127.0.0.1:8000/report/${zip}`);
    const data = await res.json();
    setReport(data);
    setLoading(false);
  };

  const downloadPDF = async () => {
    const input = document.getElementById("report-card");

    const canvas = await html2canvas(input, {
      scale: 2,
      backgroundColor: "#171a22",
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");

    const pdfWidth = 190;
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 10, 10, pdfWidth, pdfHeight);
    pdf.save(`${report.data.city}_SnapReport.pdf`);
  };

  if (report) {
    return (
      <div className="page">
        <div id="report-card" className="report-card">
          <button className="back-btn no-print" onClick={() => setReport(null)}>
            ← Back
          </button>

          <div className="report-header">
            <img src={logo} alt="Snaphomz Logo" className="report-logo" />
            <div>
              <h1>{report.data.city} Market Report</h1>
              <p className="subtitle">Generated by Snaphomz AI</p>
            </div>
          </div>

          <div className="agent-box">
            {preview && (
              <img src={preview} alt="Agent" className="agent-photo" />
            )}
            <div>
              <p><b>Agent:</b> {agentName}</p>
              <p><b>Email:</b> {agentEmail}</p>
              <p><b>Phone:</b> {agentPhone}</p>
            </div>
          </div>

          <div className="metrics-grid">
            <div><b>Median Price</b><span>{report.data.median_price}</span></div>
            <div><b>Days on Market</b><span>{report.data.days_on_market}</span></div>
            <div><b>List-to-Sale Ratio</b><span>{report.data.list_to_sale_ratio}</span></div>
            <div><b>New Listings</b><span>{report.data.new_listings}</span></div>
            <div><b>Inventory</b><span>{report.data.inventory}</span></div>
          </div>

          <h2>AI Market Narrative</h2>
          <div className="narrative">{report.narrative}</div>

          <button className="primary-btn no-print" onClick={downloadPDF}>
            Download Branded PDF
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="page">
      <div className="input-card">
        <div className="header">
          <img src={logo} alt="Snaphomz Logo" className="logo" />
          <h1>SnapReport</h1>
        </div>

        <p className="subtitle">
          AI monthly market report for Snaphomz partner agents
        </p>

        <input value={agentName} onChange={(e) => setAgentName(e.target.value)} placeholder="Agent Name" />
        <input value={agentEmail} onChange={(e) => setAgentEmail(e.target.value)} placeholder="Agent Email" />
        <input value={agentPhone} onChange={(e) => setAgentPhone(e.target.value)} placeholder="Agent Phone" />
        <input value={zip} onChange={(e) => setZip(e.target.value)} placeholder="Target Zip Code" />

        <input
          type="file"
          accept="image/*"
          onChange={(e) => {
            const file = e.target.files[0];
            if (file) setPreview(URL.createObjectURL(file));
          }}
        />

        {preview && <img src={preview} alt="Preview" className="preview-photo" />}

        <button className="primary-btn" onClick={generate}>
          {loading ? "Generating..." : "Generate Report"}
        </button>
      </div>
    </div>
  );
}

export default App;